spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id : r1
          uri : http://localhot:8081/
          predicates :
            - Path=/api/customer/**
        - id: r2
          uri: http://localhot:8082/
          predicates:
            - Path=/api/account/**
server:
  port: 8080


